/* Karloff.java */
/* Generated By:JavaCC: Do not edit this line. Karloff.java */
import java.io.*;
public class Karloff implements KarloffConstants {

  public static void main(String args[]) throws ParseException,IOException {

 Karloff analisador = new Karloff(new FileInputStream(args[0]));
 analisador.Karloff();
  }

  static final public void Karloff() throws ParseException {Token t;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIN:
      case ACHAVES:
      case FCHAVES:
      case VOID:
      case APAR:
      case FPAR:
      case VAR:
      case FLINHA:
      case FLOAT:
      case ATRIB:
      case PRINT:
      case IF:
      case WHILE:
      case RETURN:
      case BOOL:
      case PLUS:
      case MINUS:
      case MULT:
      case DIV:
      case TRUE:
      case FALSE:
      case COMP:
      case OR:
      case LESSER:
      case BIGGER:
      case AND:
      case THEN:
      case FUN:
      case VIRGULA:
      case NUM:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIN:{
        jj_consume_token(MAIN);
System.out.println("Palavra reservada: main");
        break;
        }
      case ACHAVES:{
        jj_consume_token(ACHAVES);
System.out.println("Abre chaves: {");
        break;
        }
      case FCHAVES:{
        jj_consume_token(FCHAVES);
System.out.println("Fecha chaves: }");
        break;
        }
      case NUM:{
        t = jj_consume_token(NUM);
System.out.println("N\u00famero: "+ t.image);
        break;
        }
      case ID:{
        t = jj_consume_token(ID);
System.out.println("Identificador: "+ t.image);
        break;
        }
      case VOID:{
        jj_consume_token(VOID);
System.out.println("Palavra reservada: void");
        break;
        }
      case APAR:{
        jj_consume_token(APAR);
System.out.println("Abre par\u00eanteses: (");
        break;
        }
      case FPAR:{
        jj_consume_token(FPAR);
System.out.println("Fecha par\u00eanteses: )");
        break;
        }
      case VAR:{
        jj_consume_token(VAR);
System.out.println("Palavra reservada: newVar");
        break;
        }
      case FLINHA:{
        jj_consume_token(FLINHA);
System.out.println("Ponto e v\u00edrgula: ;");
        break;
        }
      case FLOAT:{
        jj_consume_token(FLOAT);
System.out.println("Palavra reservada: float");
        break;
        }
      case ATRIB:{
        jj_consume_token(ATRIB);
System.out.println("Atribui\u00e7\u00e3o: =");
        break;
        }
      case PRINT:{
        jj_consume_token(PRINT);
System.out.println("Palavra reservada: print");
        break;
        }
      case IF:{
        jj_consume_token(IF);
System.out.println("Palavra reservada: if");
        break;
        }
      case WHILE:{
        jj_consume_token(WHILE);
System.out.println("Palavra reservada: while");
        break;
        }
      case RETURN:{
        jj_consume_token(RETURN);
System.out.println("Palavra reservada: return");
        break;
        }
      case BOOL:{
        jj_consume_token(BOOL);
System.out.println("Palavra reservada: boolean");
        break;
        }
      case PLUS:{
        jj_consume_token(PLUS);
System.out.println("Soma: +");
        break;
        }
      case MINUS:{
        jj_consume_token(MINUS);
System.out.println("Subtra\u00e7\u00e3o: -");
        break;
        }
      case MULT:{
        jj_consume_token(MULT);
System.out.println("Multiplica\u00e7\u00e3o: *");
        break;
        }
      case DIV:{
        jj_consume_token(DIV);
System.out.println("Divis\u00e3o: /");
        break;
        }
      case TRUE:{
        jj_consume_token(TRUE);
System.out.println("Verdadeiro: true");
        break;
        }
      case FALSE:{
        jj_consume_token(FALSE);
System.out.println("Falso: false");
        break;
        }
      case COMP:{
        jj_consume_token(COMP);
System.out.println("Comparador: ==");
        break;
        }
      case OR:{
        jj_consume_token(OR);
System.out.println("Ou: |");
        break;
        }
      case LESSER:{
        jj_consume_token(LESSER);
System.out.println("Menor que: <");
        break;
        }
      case BIGGER:{
        jj_consume_token(BIGGER);
System.out.println("Maior que: >");
        break;
        }
      case AND:{
        jj_consume_token(AND);
System.out.println("Comparador And: &");
        break;
        }
      case THEN:{
        jj_consume_token(THEN);
System.out.println("Palavra reservada: then");
        break;
        }
      case FUN:{
        jj_consume_token(FUN);
System.out.println("Palavra reservada: fun");
        break;
        }
      case VIRGULA:{
        jj_consume_token(VIRGULA);
System.out.println("Virgula: ,");
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(0);
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public KarloffTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[2];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0xffffffe0,0xffffffe0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0xf,0xf,};
	}

  /** Constructor with InputStream. */
  public Karloff(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Karloff(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new KarloffTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Karloff(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new KarloffTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new KarloffTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Karloff(KarloffTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(KarloffTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 2; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[36];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 2; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 36; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
